name: Java Ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml')}}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test project with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging && cp  target/*jar-with-dependencies.jar staging
      
      - name: Upload artifact@v1
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: Staging
      


